#ifndef __BOOTLOADER_CONFIG_H
#define __BOOTLOADER_CONFIG_H

#ifndef BOOTLOADER_ENABLE_USART1
#define BOOTLOADER_ENABLE_USART1        1
#endif

#ifndef BOOTLOADER_ENABLE_USART2
#define BOOTLOADER_ENABLE_USART2        0
#endif

#ifndef BOOTLOADER_ENABLE_USART3
#define BOOTLOADER_ENABLE_USART3        0
#endif

#if !(BOOTLOADER_ENABLE_USART1) && \
    !(BOOTLOADER_ENABLE_USART2) && \
    !(BOOTLOADER_ENABLE_USART3)
#error "At least one Bootloader USART must be enabled"
#endif

#ifndef BOOTLOADER_ENABLE_GOWIN_FPGA
#define BOOTLOADER_ENABLE_GOWIN_FPGA    0
#endif

#ifndef BOOTLOADER_ENABLE_ANLOGIC_FPGA
#define BOOTLOADER_ENABLE_ANLOGIC_FPGA  0
#endif

#if (BOOTLOADER_ENABLE_GOWIN_FPGA) && \
    (BOOTLOADER_ENABLE_ANLOGIC_FPGA)
#error "Gowin and Anlogic FPGA backends are mutually exclusive"
#endif

#endif /* __BOOTLOADER_CONFIG_H */
